# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Create CarClass data
CarClass.create!(:no => '1100', :name => '自強', :en_name => 'Tze-Chiang Limited Express')
CarClass.create!(:no => '1101', :name => '自強', :en_name => 'Tze-Chiang Limited Express')
CarClass.create!(:no => '1102', :name => '太魯閣號', :en_name => 'Tze-Chiang Limited Express')
CarClass.create!(:no => '1107', :name => '普悠瑪號', :en_name => 'Tze-Chiang Limited Express')
CarClass.create!(:no => '1110', :name => '莒光', :en_name => 'Chu-Kuang Express')
CarClass.create!(:no => '1120', :name => '復興', :en_name => 'Fu-Hsing Semi Express')
CarClass.create!(:no => '1130', :name => '電車', :en_name => 'Electric Multiple Unit')
CarClass.create!(:no => '1131', :name => '區間車', :en_name => 'Local Train')
CarClass.create!(:no => '1132', :name => '區間快', :en_name => 'Fast Local Train')
CarClass.create!(:no => '1140', :name => '普快車', :en_name => 'Ordinary Train')
CarClass.create!(:no => '1141', :name => '柴快車', :en_name => 'Disel Rail Car')
CarClass.create!(:no => '1150', :name => '柴油車', :en_name => 'na')

# Create Station data
Station.create!(:no => '1001', :name => '基隆', :en_name => 'Keelung', :ticket_no => '092')
Station.create!(:no => '1002', :name => '八堵', :en_name => 'Badu', :ticket_no => '093')
Station.create!(:no => '1003', :name => '七堵', :en_name => 'Cidu', :ticket_no => '094')
Station.create!(:no => '1004', :name => '五堵', :en_name => 'Wudu', :ticket_no => '')
Station.create!(:no => '1005', :name => '汐止', :en_name => 'Sijhih', :ticket_no => '096')
Station.create!(:no => '1006', :name => '南港', :en_name => 'Nangang', :ticket_no => '097')
Station.create!(:no => '1007', :name => '松山', :en_name => 'Songshan', :ticket_no => '098')
Station.create!(:no => '1008', :name => '台北', :en_name => 'Taipei', :ticket_no => '100')
Station.create!(:no => '1009', :name => '萬華', :en_name => 'Wanhua', :ticket_no => '101')
Station.create!(:no => '1011', :name => '板橋', :en_name => 'Banciao', :ticket_no => '102')
Station.create!(:no => '1032', :name => '浮洲', :en_name => 'Fuzhou', :ticket_no => '')
Station.create!(:no => '1012', :name => '樹林', :en_name => 'Shulin', :ticket_no => '103')
Station.create!(:no => '1013', :name => '山佳', :en_name => 'Shanjia', :ticket_no => '104')
Station.create!(:no => '1014', :name => '鶯歌', :en_name => 'Yingge', :ticket_no => '105')
Station.create!(:no => '1015', :name => '桃園', :en_name => 'Taoyuan', :ticket_no => '106')
Station.create!(:no => '1016', :name => '內壢', :en_name => 'Neili', :ticket_no => '107')
Station.create!(:no => '1017', :name => '中壢', :en_name => 'Jhongli', :ticket_no => '108')
Station.create!(:no => '1018', :name => '埔心', :en_name => 'Pusin', :ticket_no => '109')
Station.create!(:no => '1019', :name => '楊梅', :en_name => 'Yangmei', :ticket_no => '110')
Station.create!(:no => '1020', :name => '富岡', :en_name => 'Fugang', :ticket_no => '111')
Station.create!(:no => '1021', :name => '湖口', :en_name => 'Hukou', :ticket_no => '112')
Station.create!(:no => '1022', :name => '新豐', :en_name => 'Sinfong', :ticket_no => '113')
Station.create!(:no => '1023', :name => '竹北', :en_name => 'Jhubei', :ticket_no => '114')
Station.create!(:no => '1024', :name => '北新竹', :en_name => 'North Hsinchu', :ticket_no => '')
Station.create!(:no => '1025', :name => '新竹', :en_name => 'Hsinchu', :ticket_no => '115')
Station.create!(:no => '1026', :name => '香山', :en_name => 'Siangshan', :ticket_no => '')
Station.create!(:no => '1027', :name => '崎頂', :en_name => 'Ciding', :ticket_no => '')
Station.create!(:no => '1028', :name => '竹南', :en_name => 'Jhunan', :ticket_no => '118')
Station.create!(:no => '1029', :name => '三坑', :en_name => 'Sankeng', :ticket_no => '')
Station.create!(:no => '1030', :name => '百福', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1031', :name => '汐科', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1102', :name => '談文', :en_name => 'Tanwan', :ticket_no => '119')
Station.create!(:no => '1103', :name => '談文南', :en_name => 'Tanwannan', :ticket_no => '')
Station.create!(:no => '1104', :name => '大山', :en_name => 'Dashan', :ticket_no => '120')
Station.create!(:no => '1105', :name => '後龍', :en_name => 'Houlong', :ticket_no => '121')
Station.create!(:no => '1106', :name => '龍港', :en_name => 'Longgang', :ticket_no => '')
Station.create!(:no => '1107', :name => '白沙屯', :en_name => 'Baishatun', :ticket_no => '123')
Station.create!(:no => '1108', :name => '新埔', :en_name => 'Sinpu', :ticket_no => '124')
Station.create!(:no => '1109', :name => '通霄', :en_name => 'Tongsiao', :ticket_no => '125')
Station.create!(:no => '1110', :name => '苑裡', :en_name => 'Yuanli', :ticket_no => '126')
Station.create!(:no => '1111', :name => '日南', :en_name => 'Rihnan', :ticket_no => '127')
Station.create!(:no => '1112', :name => '大甲', :en_name => 'Dajia', :ticket_no => '128')
Station.create!(:no => '1113', :name => '台中港', :en_name => 'Taichung Port', :ticket_no => '129')
Station.create!(:no => '1114', :name => '清水', :en_name => 'Cingshuei', :ticket_no => '130')
Station.create!(:no => '1115', :name => '沙鹿', :en_name => 'Shalu', :ticket_no => '131')
Station.create!(:no => '1116', :name => '龍井', :en_name => 'Longjing', :ticket_no => '132')
Station.create!(:no => '1117', :name => '大肚', :en_name => 'Dadu', :ticket_no => '133')
Station.create!(:no => '1118', :name => '追分', :en_name => 'Jhuifen', :ticket_no => '134')
Station.create!(:no => '1119', :name => '大肚溪南', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1120', :name => '彰化', :en_name => 'Changhua', :ticket_no => '149')
Station.create!(:no => '1202', :name => '花壇', :en_name => 'Huatan', :ticket_no => '150')
Station.create!(:no => '1203', :name => '員林', :en_name => 'Yuanlin', :ticket_no => '151')
Station.create!(:no => '1204', :name => '永靖', :en_name => 'Yongjing', :ticket_no => '')
Station.create!(:no => '1205', :name => '社頭', :en_name => 'Shetou', :ticket_no => '153')
Station.create!(:no => '1206', :name => '田中', :en_name => 'Tianjhong', :ticket_no => '154')
Station.create!(:no => '1207', :name => '二水', :en_name => 'Ershuei', :ticket_no => '155')
Station.create!(:no => '1208', :name => '林內', :en_name => 'Linnei', :ticket_no => '156')
Station.create!(:no => '1209', :name => '石榴', :en_name => 'Shihliou', :ticket_no => '')
Station.create!(:no => '1210', :name => '斗六', :en_name => 'Douliou', :ticket_no => '158')
Station.create!(:no => '1211', :name => '斗南', :en_name => 'Dounan', :ticket_no => '159')
Station.create!(:no => '1212', :name => '石龜', :en_name => 'Shihguei', :ticket_no => '')
Station.create!(:no => '1213', :name => '大林', :en_name => 'Dalin', :ticket_no => '161')
Station.create!(:no => '1214', :name => '民雄', :en_name => 'Minsyong', :ticket_no => '162')
Station.create!(:no => '1215', :name => '嘉義', :en_name => 'Chiayi', :ticket_no => '163')
Station.create!(:no => '1217', :name => '水上', :en_name => 'Shueishang', :ticket_no => '164')
Station.create!(:no => '1218', :name => '南靖', :en_name => 'Nanjing', :ticket_no => '')
Station.create!(:no => '1219', :name => '後壁', :en_name => 'Houbi', :ticket_no => '166')
Station.create!(:no => '1220', :name => '新營', :en_name => 'Sinying', :ticket_no => '167')
Station.create!(:no => '1221', :name => '柳營', :en_name => 'Liouying', :ticket_no => '')
Station.create!(:no => '1222', :name => '林鳳營', :en_name => 'Linfongying', :ticket_no => '169')
Station.create!(:no => '1223', :name => '隆田', :en_name => 'Longtian', :ticket_no => '170')
Station.create!(:no => '1224', :name => '拔林', :en_name => 'Balin', :ticket_no => '171')
Station.create!(:no => '1225', :name => '善化', :en_name => 'Shanhua', :ticket_no => '172')
Station.create!(:no => '1226', :name => '新市', :en_name => 'Sinshih', :ticket_no => '173')
Station.create!(:no => '1227', :name => '永康', :en_name => 'Yongkang', :ticket_no => '174')
Station.create!(:no => '1228', :name => '台南', :en_name => 'Tainan', :ticket_no => '175')
Station.create!(:no => '1229', :name => '保安', :en_name => 'Baoan', :ticket_no => '176')
Station.create!(:no => '1230', :name => '中洲', :en_name => 'Jhongjhou', :ticket_no => '177')
Station.create!(:no => '1231', :name => '大湖', :en_name => 'Dahu', :ticket_no => '178')
Station.create!(:no => '1232', :name => '路竹', :en_name => 'Lujhu', :ticket_no => '179')
Station.create!(:no => '1233', :name => '岡山', :en_name => 'Gangshan', :ticket_no => '180')
Station.create!(:no => '1234', :name => '橋頭', :en_name => 'Ciaotou', :ticket_no => '181')
Station.create!(:no => '1235', :name => '楠梓', :en_name => 'Nanzih', :ticket_no => '183')
Station.create!(:no => '1236', :name => '左營', :en_name => 'Zuoying', :ticket_no => '184')
Station.create!(:no => '1237', :name => '鼓山', :en_name => 'Gushan', :ticket_no => '')
Station.create!(:no => '1238', :name => '高雄', :en_name => 'Kaohsiung', :ticket_no => '185')
Station.create!(:no => '1239', :name => '大橋', :en_name => 'Daciao', :ticket_no => '')
Station.create!(:no => '1240', :name => '大村', :en_name => 'Datsun', :ticket_no => '')
Station.create!(:no => '1241', :name => '嘉北', :en_name => 'ChiaPei', :ticket_no => '')
Station.create!(:no => '1242', :name => '新左營', :en_name => 'na', :ticket_no => '288')
Station.create!(:no => '1302', :name => '造橋', :en_name => 'Zaociao', :ticket_no => '135')
Station.create!(:no => '1304', :name => '豐富', :en_name => 'Fongfu', :ticket_no => '')
Station.create!(:no => '1305', :name => '苗栗', :en_name => 'Miaoli', :ticket_no => '137')
Station.create!(:no => '1307', :name => '南勢', :en_name => 'Nanshih', :ticket_no => '')
Station.create!(:no => '1308', :name => '銅鑼', :en_name => 'Tongluo', :ticket_no => '139')
Station.create!(:no => '1310', :name => '三義', :en_name => 'Sanyi', :ticket_no => '140')
Station.create!(:no => '1314', :name => '泰安', :en_name => 'Taian', :ticket_no => '142')
Station.create!(:no => '1315', :name => '后里', :en_name => 'Houli', :ticket_no => '143')
Station.create!(:no => '1317', :name => '豐原', :en_name => 'Fongyuan', :ticket_no => '144')
Station.create!(:no => '1318', :name => '潭子', :en_name => 'Tanzih', :ticket_no => '145')
Station.create!(:no => '1319', :name => '台中', :en_name => 'Taichung', :ticket_no => '146')
Station.create!(:no => '1320', :name => '烏日', :en_name => 'Wurih', :ticket_no => '147')
Station.create!(:no => '1321', :name => '成功', :en_name => 'Chenggong', :ticket_no => '148')
Station.create!(:no => '1322', :name => '大慶', :en_name => 'Dacing', :ticket_no => '223')
Station.create!(:no => '1323', :name => '太原', :en_name => 'Taiyuan', :ticket_no => '')
Station.create!(:no => '1324', :name => '新烏日', :en_name => 'na', :ticket_no => '280')
Station.create!(:no => '1402', :name => '鳳山', :en_name => 'Fongshan', :ticket_no => '186')
Station.create!(:no => '1403', :name => '後庄', :en_name => 'Houjhuang', :ticket_no => '187')
Station.create!(:no => '1404', :name => '九曲堂', :en_name => 'Jioucyutang', :ticket_no => '188')
Station.create!(:no => '1405', :name => '六塊厝', :en_name => 'Lioukuaicuo', :ticket_no => '')
Station.create!(:no => '1406', :name => '屏東', :en_name => 'Pingtung', :ticket_no => '190')
Station.create!(:no => '1407', :name => '歸來', :en_name => 'Gueilai', :ticket_no => '')
Station.create!(:no => '1408', :name => '麟洛', :en_name => 'Linluo', :ticket_no => '')
Station.create!(:no => '1409', :name => '西勢', :en_name => 'Sishih', :ticket_no => '193')
Station.create!(:no => '1410', :name => '竹田', :en_name => 'Jhutian', :ticket_no => '194')
Station.create!(:no => '1411', :name => '潮州', :en_name => 'Chaojhou', :ticket_no => '195')
Station.create!(:no => '1412', :name => '崁頂', :en_name => 'Kanding', :ticket_no => '')
Station.create!(:no => '1413', :name => '南州', :en_name => 'Nanjhou', :ticket_no => '197')
Station.create!(:no => '1414', :name => '鎮安', :en_name => 'Jhenan', :ticket_no => '')
Station.create!(:no => '1415', :name => '林邊', :en_name => 'Linbian', :ticket_no => '199')
Station.create!(:no => '1416', :name => '佳冬', :en_name => 'Jiadong', :ticket_no => '200')
Station.create!(:no => '1417', :name => '東海', :en_name => 'Donghai', :ticket_no => '')
Station.create!(:no => '1418', :name => '枋寮', :en_name => 'Fangliao', :ticket_no => '203')
Station.create!(:no => '1502', :name => '加祿', :en_name => 'Jialu', :ticket_no => '204')
Station.create!(:no => '1503', :name => '內獅', :en_name => 'Neishih', :ticket_no => '')
Station.create!(:no => '1504', :name => '枋山', :en_name => 'Fangshan', :ticket_no => '')
Station.create!(:no => '1505', :name => '枋野', :en_name => 'Fangye', :ticket_no => '')
Station.create!(:no => '1506', :name => '中央', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1507', :name => '古莊', :en_name => 'Gujhuang', :ticket_no => '')
Station.create!(:no => '1508', :name => '大武', :en_name => 'Dawu', :ticket_no => '211')
Station.create!(:no => '1510', :name => '瀧溪', :en_name => 'Lunghsi', :ticket_no => '213')
Station.create!(:no => '1511', :name => '多良', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1512', :name => '金崙', :en_name => 'Jinlun', :ticket_no => '215')
Station.create!(:no => '1514', :name => '太麻里', :en_name => 'Taimali', :ticket_no => '217')
Station.create!(:no => '1516', :name => '知本', :en_name => 'Jhihben', :ticket_no => '219')
Station.create!(:no => '1517', :name => '康樂', :en_name => 'Kangle', :ticket_no => '220')
Station.create!(:no => '1602', :name => '吉安', :en_name => 'Jian', :ticket_no => '045')
Station.create!(:no => '1604', :name => '志學', :en_name => 'Jhihsyue', :ticket_no => '043')
Station.create!(:no => '1605', :name => '平和', :en_name => 'Pinghe', :ticket_no => '')
Station.create!(:no => '1606', :name => '壽豐', :en_name => 'Shoufong', :ticket_no => '041')
Station.create!(:no => '1607', :name => '豐田', :en_name => 'Fongtian', :ticket_no => '040')
Station.create!(:no => '1608', :name => '溪口', :en_name => 'Sikou', :ticket_no => '')
Station.create!(:no => '1609', :name => '南平', :en_name => 'Nanping', :ticket_no => '037')
Station.create!(:no => '1610', :name => '鳳林', :en_name => 'Fonglin', :ticket_no => '036')
Station.create!(:no => '1611', :name => '萬榮', :en_name => 'Wanrong', :ticket_no => '035')
Station.create!(:no => '1612', :name => '光復', :en_name => 'Guangfu', :ticket_no => '034')
Station.create!(:no => '1613', :name => '大富', :en_name => 'Dafu', :ticket_no => '')
Station.create!(:no => '1614', :name => '富源', :en_name => 'Fuyuan', :ticket_no => '031')
Station.create!(:no => '1616', :name => '瑞穗', :en_name => 'Rueisuei', :ticket_no => '029')
Station.create!(:no => '1617', :name => '三民', :en_name => 'Sanmin', :ticket_no => '')
Station.create!(:no => '1619', :name => '玉里', :en_name => 'Yuli', :ticket_no => '025')
Station.create!(:no => '1620', :name => '安通', :en_name => 'Antung', :ticket_no => '')
Station.create!(:no => '1621', :name => '東里', :en_name => 'Dongli', :ticket_no => '022')
Station.create!(:no => '1622', :name => '東竹', :en_name => 'Dongjhu', :ticket_no => '020')
Station.create!(:no => '1623', :name => '富里', :en_name => 'Fuli', :ticket_no => '018')
Station.create!(:no => '1624', :name => '池上', :en_name => 'Chihshang', :ticket_no => '015')
Station.create!(:no => '1625', :name => '海端', :en_name => 'Haiduan', :ticket_no => '')
Station.create!(:no => '1626', :name => '關山', :en_name => 'Guanshan', :ticket_no => '012')
Station.create!(:no => '1627', :name => '月美', :en_name => 'Yuemei', :ticket_no => '')
Station.create!(:no => '1628', :name => '瑞和', :en_name => 'Rueihe', :ticket_no => '')
Station.create!(:no => '1629', :name => '瑞源', :en_name => 'Rueiyuan', :ticket_no => '009')
Station.create!(:no => '1630', :name => '鹿野', :en_name => 'Luye', :ticket_no => '008')
Station.create!(:no => '1631', :name => '山里', :en_name => 'Shanli', :ticket_no => '')
Station.create!(:no => '1632', :name => '台東', :en_name => 'Taitung', :ticket_no => '004')
Station.create!(:no => '1633', :name => '馬(廢)蘭', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1634', :name => '台(廢)東', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1635', :name => '舞鶴', :en_name => 'Wuhe', :ticket_no => '')
Station.create!(:no => '1703', :name => '永樂', :en_name => 'Yongle', :ticket_no => '')
Station.create!(:no => '1704', :name => '東澳', :en_name => 'Dongao', :ticket_no => '063')
Station.create!(:no => '1705', :name => '南澳', :en_name => 'Nanao', :ticket_no => '062')
Station.create!(:no => '1706', :name => '武塔', :en_name => 'Wuta', :ticket_no => '')
Station.create!(:no => '1708', :name => '漢本', :en_name => 'Hanben', :ticket_no => '')
Station.create!(:no => '1709', :name => '和平', :en_name => 'Heping', :ticket_no => '057')
Station.create!(:no => '1710', :name => '和仁', :en_name => 'Horen', :ticket_no => '056')
Station.create!(:no => '1711', :name => '崇德', :en_name => 'Chongde', :ticket_no => '055')
Station.create!(:no => '1712', :name => '新城', :en_name => 'Sincheng', :ticket_no => '054')
Station.create!(:no => '1713', :name => '景美', :en_name => 'Jingmei', :ticket_no => '')
Station.create!(:no => '1714', :name => '北埔', :en_name => 'Beipu', :ticket_no => '052')
Station.create!(:no => '1715', :name => '花蓮', :en_name => 'Hualien', :ticket_no => '051')
Station.create!(:no => '1802', :name => '暖暖', :en_name => 'Nuannuan', :ticket_no => '')
Station.create!(:no => '1803', :name => '四腳亭', :en_name => 'Sihjiaoting', :ticket_no => '090')
Station.create!(:no => '1804', :name => '瑞芳', :en_name => 'Rueifang', :ticket_no => '089')
Station.create!(:no => '1805', :name => '侯硐', :en_name => 'Houtung', :ticket_no => '088')
Station.create!(:no => '1806', :name => '三貂嶺', :en_name => 'Sandiaoling', :ticket_no => '087')
Station.create!(:no => '1807', :name => '牡丹', :en_name => 'Mudan', :ticket_no => '086')
Station.create!(:no => '1808', :name => '雙溪', :en_name => 'Shuangsi', :ticket_no => '085')
Station.create!(:no => '1809', :name => '貢寮', :en_name => 'Gungliao', :ticket_no => '084')
Station.create!(:no => '1810', :name => '福隆', :en_name => 'Fulong', :ticket_no => '083')
Station.create!(:no => '1811', :name => '石城', :en_name => 'Shihcheng', :ticket_no => '')
Station.create!(:no => '1812', :name => '大里', :en_name => 'Dali', :ticket_no => '081')
Station.create!(:no => '1813', :name => '大溪', :en_name => 'Dasi', :ticket_no => '080')
Station.create!(:no => '1814', :name => '龜山', :en_name => 'Gueishan', :ticket_no => '079')
Station.create!(:no => '1815', :name => '外澳', :en_name => 'Waiao', :ticket_no => '')
Station.create!(:no => '1816', :name => '頭城', :en_name => 'Toucheng', :ticket_no => '077')
Station.create!(:no => '1817', :name => '頂埔', :en_name => 'Dingpu', :ticket_no => '')
Station.create!(:no => '1818', :name => '礁溪', :en_name => 'Jiaohsi', :ticket_no => '075')
Station.create!(:no => '1819', :name => '四城', :en_name => 'Sihcheng', :ticket_no => '074')
Station.create!(:no => '1820', :name => '宜蘭', :en_name => 'Yilan', :ticket_no => '073')
Station.create!(:no => '1821', :name => '二結', :en_name => 'Erjie', :ticket_no => '072')
Station.create!(:no => '1822', :name => '中里', :en_name => 'Jhongli', :ticket_no => '')
Station.create!(:no => '1823', :name => '羅東', :en_name => 'Luodong', :ticket_no => '070')
Station.create!(:no => '1824', :name => '冬山', :en_name => 'Dongshan', :ticket_no => '069')
Station.create!(:no => '1825', :name => '新馬', :en_name => 'Sinma', :ticket_no => '')
Station.create!(:no => '1826', :name => '蘇澳新', :en_name => 'Suaosin', :ticket_no => '067')
Station.create!(:no => '1827', :name => '蘇澳', :en_name => 'Suao', :ticket_no => '066')
Station.create!(:no => '1903', :name => '大華', :en_name => 'Dahua', :ticket_no => '')
Station.create!(:no => '1904', :name => '十分', :en_name => 'Shihfen', :ticket_no => '232')
Station.create!(:no => '1905', :name => '望古', :en_name => 'Wanggu', :ticket_no => '')
Station.create!(:no => '1906', :name => '嶺腳', :en_name => 'Lingjiao', :ticket_no => '')
Station.create!(:no => '1907', :name => '平溪', :en_name => 'Pingsi', :ticket_no => '235')
Station.create!(:no => '1908', :name => '菁桐', :en_name => 'Jingtong', :ticket_no => '')
Station.create!(:no => '2002', :name => '深澳', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2102', :name => '五福', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2103', :name => '林口', :en_name => 'Linkou', :ticket_no => '')
Station.create!(:no => '2104', :name => '電廠', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2105', :name => '桃中', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2106', :name => '寶山', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2107', :name => '南祥', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2108', :name => '長興', :en_name => 'Hengshan', :ticket_no => '')
Station.create!(:no => '2109', :name => '海山站', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2110', :name => '海湖站', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '2212', :name => '千甲', :en_name => 'Qianjia', :ticket_no => '')
Station.create!(:no => '2213', :name => '新莊', :en_name => 'Xinzhuang', :ticket_no => '')
Station.create!(:no => '2203', :name => '竹中', :en_name => 'Jhujhong', :ticket_no => '')
Station.create!(:no => '2214', :name => '六家', :en_name => 'Liujia', :ticket_no => '')
Station.create!(:no => '2204', :name => '上員', :en_name => 'Shangyuan', :ticket_no => '')
Station.create!(:no => '2205', :name => '竹東', :en_name => 'Jhudong', :ticket_no => '')
Station.create!(:no => '2206', :name => '橫山', :en_name => 'Hengshan', :ticket_no => '')
Station.create!(:no => '2207', :name => '九讚頭', :en_name => 'jiouzantou', :ticket_no => '')
Station.create!(:no => '2208', :name => '合興', :en_name => 'Hesing', :ticket_no => '')
Station.create!(:no => '2209', :name => '富貴', :en_name => 'Fuguei', :ticket_no => '')
Station.create!(:no => '2210', :name => '內灣', :en_name => 'Neiwan', :ticket_no => '248')
Station.create!(:no => '2211', :name => '榮華', :en_name => 'Ronghua', :ticket_no => '')
Station.create!(:no => '2302', :name => '台中港貨', :en_name => 'Taichung Port', :ticket_no => '')
Station.create!(:no => '2402', :name => '龍井煤場', :en_name => 'Longjing', :ticket_no => '')
Station.create!(:no => '2502', :name => '神岡', :en_name => 'Shangang', :ticket_no => '')
Station.create!(:no => '2702', :name => '源泉', :en_name => 'Yuanciyuan', :ticket_no => '')
Station.create!(:no => '2703', :name => '濁水', :en_name => 'Jhuoshuei', :ticket_no => '')
Station.create!(:no => '2704', :name => '龍泉', :en_name => 'Lungcyuan', :ticket_no => '')
Station.create!(:no => '2705', :name => '集集', :en_name => 'Jiji', :ticket_no => '')
Station.create!(:no => '2706', :name => '水里', :en_name => 'Shueili', :ticket_no => '')
Station.create!(:no => '2707', :name => '車埕', :en_name => 'Checheng', :ticket_no => '256')
Station.create!(:no => '2802', :name => '南調', :en_name => 'Nandiao', :ticket_no => '')
Station.create!(:no => '2902', :name => '高雄港', :en_name => 'Kaohsiung Port', :ticket_no => '')
Station.create!(:no => '3102', :name => '前鎮', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '3202', :name => '花蓮港', :en_name => 'hualien Port', :ticket_no => '')
Station.create!(:no => '3302', :name => '中興一號', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '3402', :name => '中興二號', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '3902', :name => '機廠', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '4102', :name => '樹調', :en_name => 'ShuDiao', :ticket_no => '')
Station.create!(:no => '4202', :name => '東港支線', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '4302', :name => '東南支線', :en_name => 'na', :ticket_no => '')
Station.create!(:no => '1244', :name => '南科', :en_name => 'Nanke', :ticket_no => '')
Station.create!(:no => '5101', :name => '長榮大學', :en_name => 'Chang Jung Christian University', :ticket_no => '')
Station.create!(:no => '5102', :name => '沙崙', :en_name => 'Shalun', :ticket_no => '')
Station.create!(:no => '1033', :name => '北湖', :en_name => 'BaiHwu', :ticket_no => '')

